application: godatacloud
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers: 
        - url: /([0-9]*)
          script: uploadfile.app
        - url: /uploaded
          script: fileuploaded.app
        - url: /images
          static_dir: images
        - url: /thumbnail/([0-9]*)
          script: thumbnail.app
        - url: /file/([0-9]+)/download
          script: filedownload.app
        - url: /delete/(.*)
          script: delete.app
        - url: /client
          script: clientserver.app
